# Generated by Django 4.2.6 on 2023-10-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=20)),
                ('poster', models.URLField()),
            ],
        ),
    ]
