# Generated by Django 4.2.6 on 2023-10-20 18:32

from django.db import migrations, models

import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.CharField(default=movies.models.generate_id, max_length=10, primary_key=True, serialize=False),
        ),
    ]
